"""empty message

Revision ID: 05c744be226a
Revises: da1854c3d4e4
Create Date: 2020-10-16 11:55:48.452720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c744be226a'
down_revision = 'da1854c3d4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
