"""Update User table

Revision ID: 13215a9d4c67
Revises: 2371cf7eb8bf
Create Date: 2020-10-17 04:47:26.979356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13215a9d4c67'
down_revision = '2371cf7eb8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['lastName'])
    op.create_unique_constraint(None, 'users', ['firstName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
