"""empty message

Revision ID: 1e85977a645e
Revises: 79d7188cc3b7
Create Date: 2020-10-16 11:51:33.512127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e85977a645e'
down_revision = '79d7188cc3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
