"""Create Muscle table

Revision ID: 2cff2ef18bc7
Revises: 89093f779acf
Create Date: 2020-10-16 12:46:42.539982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cff2ef18bc7'
down_revision = '89093f779acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muscles')
    # ### end Alembic commands ###
