"""Update Exercise table

Revision ID: 331f6a084ed4
Revises: ce3fb5087e5c
Create Date: 2020-10-16 17:43:29.671381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331f6a084ed4'
down_revision = 'ce3fb5087e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'equipmentId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'equipmentId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
