"""empty message

Revision ID: 33de7abcae37
Revises: fb3dae8a1201
Create Date: 2020-10-16 12:00:57.878268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33de7abcae37'
down_revision = 'fb3dae8a1201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    # ### end Alembic commands ###
