"""Create Instruction table

Revision ID: 454aa419fb0f
Revises: 52209abb6c38
Create Date: 2020-10-16 12:20:59.635487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454aa419fb0f'
down_revision = '52209abb6c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('exerciseId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exerciseId'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructions')
    # ### end Alembic commands ###
