"""Create Exercises_Muscles table

Revision ID: 46a78c5dd704
Revises: 331f6a084ed4
Create Date: 2020-10-16 18:14:17.726512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a78c5dd704'
down_revision = '331f6a084ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises_muscles', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises_muscles', 'id')
    # ### end Alembic commands ###
