"""empty message

Revision ID: 471ae4fde2f7
Revises: 3f355bd9154a
Create Date: 2020-10-16 11:52:59.480777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471ae4fde2f7'
down_revision = '3f355bd9154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
