"""Create Exercise table

Revision ID: 52209abb6c38
Revises: 71b14fe3ccfa
Create Date: 2020-10-16 12:02:59.834792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52209abb6c38'
down_revision = '71b14fe3ccfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bbPageUrl', sa.String(length=255), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('equipmentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipmentId'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['exercise_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
