"""Create Exercise_Type table

Revision ID: 71b14fe3ccfa
Revises: 33de7abcae37
Create Date: 2020-10-16 12:02:19.941152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b14fe3ccfa'
down_revision = '33de7abcae37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_types')
    # ### end Alembic commands ###
