"""empty message

Revision ID: 79d7188cc3b7
Revises: d425e568f656
Create Date: 2020-10-16 11:48:37.626693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d7188cc3b7'
down_revision = 'd425e568f656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondtests')
    op.drop_table('tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'name', name='tests_pkey'),
    sa.UniqueConstraint('name', name='tests_name_key')
    )
    op.create_table('secondtests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='secondtests_pkey'),
    sa.UniqueConstraint('name', name='secondtests_name_key')
    )
    # ### end Alembic commands ###
