"""Update User table

Revision ID: 7b3fa226df2e
Revises: 13215a9d4c67
Create Date: 2020-10-17 05:04:40.557725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3fa226df2e'
down_revision = '13215a9d4c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
