"""Revise Exercise

Revision ID: 7c3fdb055460
Revises: 0c831ce93f8a
Create Date: 2020-10-17 19:15:28.325046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3fdb055460'
down_revision = '0c831ce93f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
