"""Update Exercises_Muscles table

Revision ID: 7dc714657d62
Revises: 46a78c5dd704
Create Date: 2020-10-16 18:17:19.677205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc714657d62'
down_revision = '46a78c5dd704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
