"""Create Routine table

Revision ID: 89f144bb123d
Revises: 871ca9a53fd4
Create Date: 2020-10-16 12:50:20.651866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f144bb123d'
down_revision = '871ca9a53fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programId'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routines')
    # ### end Alembic commands ###
