"""Update Exercises_Muscles table

Revision ID: bc340c5b4097
Revises: 7dc714657d62
Create Date: 2020-10-16 18:22:36.208249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc340c5b4097'
down_revision = '7dc714657d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
