"""Create Media table

Revision ID: c84ac1b1af37
Revises: f89ddd51223b
Create Date: 2020-10-16 12:44:01.399579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84ac1b1af37'
down_revision = 'f89ddd51223b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
