"""Update Media migration

Revision ID: ce3fb5087e5c
Revises: 05de8842b6c6
Create Date: 2020-10-16 14:25:14.853509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3fb5087e5c'
down_revision = '05de8842b6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
