"""Revise User

Revision ID: d76d80b8371f
Revises: 7c3fdb055460
Create Date: 2020-10-24 10:21:03.318385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76d80b8371f'
down_revision = '7c3fdb055460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
