"""empty message

Revision ID: da1854c3d4e4
Revises: 471ae4fde2f7
Create Date: 2020-10-16 11:54:38.155815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1854c3d4e4'
down_revision = '471ae4fde2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
