"""empty message

Revision ID: fb3dae8a1201
Revises: 05c744be226a
Create Date: 2020-10-16 11:57:23.094202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3dae8a1201'
down_revision = '05c744be226a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'name', name='equipment_pkey'),
    sa.UniqueConstraint('name', name='equipment_name_key')
    )
    # ### end Alembic commands ###
